version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: qbittorrent-api
    versions:
    - 2021.1.16
    - 2021.2.17
    - 2021.3.18
    - 2021.4.19
  - dependency-name: regex
    versions:
    - 2021.3.17
  - dependency-name: pillow
    versions:
    - 8.1.1
    - 8.1.2
  - dependency-name: python-telegram-bot
    versions:
    - "13.2"
    - "13.3"
  - dependency-name: wolframalpha
    versions:
    - 5.0.0
  - dependency-name: gtts
    versions:
    - 2.2.2
  - dependency-name: howlongtobeatpy
    versions:
    - 0.1.16
    - 0.1.17
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: pyyaml
    versions:
    - 5.4.1
  - dependency-name: mysql-connector-python
    versions:
    - 8.0.23
