os: linux
dist: bionic
language: python
python:
- '3.7'
install:
  - pip install -r requirements.txt
addons:
  ssh_known_hosts:
  - "$HOSTNAME"
before_script:
- echo -e "Host $HOSTNAME\n\tStrictHostKeyChecking no" >> ~/.ssh/config
jobs:
  include:
  - stage: flake8 test
    if: type = pull_request AND branch = master
    script: flake8 .
before_deploy:
  - openssl aes-256-cbc -K $encrypted_05d4d4358b2c_key -iv $encrypted_05d4d4358b2c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh bot superseriousbot
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh travis-testing weirdindianbot
    on:
      branch: travisci-testing
