[tool.poetry]
name = "SuperSeriousBot"
version = "2.0.0"
description = ""
authors = ["Ayaan Zaidi <hi@obviy.us>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
Cerberus = "^1.3.4"
redis = "^4.5.1"
redvid = "^1.2.0"
python-telegram-bot = { version = "^20.1", allow-prereleases = true, extras = [
    "rate-limiter",
    "job-queue",
    "webhooks"
] }
yt-dlp = "^2023.3.4"
asyncpraw = "^7.7.0"
dateparser = "^1.1.7"
coloredlogs = "^15.0.1"
howlongtobeatpy = "^1.0.5"
spurdify = "^0.3.0"
translatepy = "^2.3"
uwuify = "^1.2.1"
geopy = "^2.3.0"
httpx = "^0.23.3"
pyvis = "^0.3.2"
cinemagoer = "^2022.12.27"
networkx = "^3.0"
openai = "^0.27.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
