[tool.poetry]
name = "SuperSeriousBot"
version = "2.0.0"
description = ""
authors = ["Ayaan Zaidi <hi@obviy.us>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
Cerberus = "^1.3.5"
redvid = "^2.0.5"
python-telegram-bot = { version = "^21.3", extras = [
    "rate-limiter",
    "job-queue",
    "webhooks",
] }
yt-dlp = "^2024.7.9"
asyncpraw = "^7.7.1"
dateparser = "^1.2.0"
coloredlogs = "^15.0.1"
howlongtobeatpy = "^1.0.5"
spurdify = "^0.3.0"
uwuify = "^1.3.1"
geopy = "^2.4.1"
pyvis = "^0.3.2"
networkx = "^3.3"
rotten-tomatoes-client = "^0.0.3"
beautifulsoup4 = "^4.12.3"
cinemagoer = { git = "https://github.com/cinemagoer/cinemagoer" }
async-lru = "^2.0.4"
aiosqlite = "0.17.0"
ijson = "^3.3.0"
litellm = "^1.41.15"
deep-translator = "^1.11.4"
translatepy = "^2.3"
aiohttp = "^3.9.5"
caribou = "^0.3.0"
redis = "^5.0.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
